### ISSUE TITLE
CSS filters not being applied in the css3filters demo

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#104]
@molant Filters are not being applied in css3filters demo in Microsoft Edge, which breaks the functionality of the demo. It doesn't appear to be a CSS issue, but rather `filter:none` is being applied inline on the images via the JavaScript. Works as expected in Chrome and FF.

It appears @sayar is the author of this demo but I can't set him as the assignee here.

**Comment by molant** [comment]
Are the filters activated in about:flags?

-----Original Message-----

**Comment by melanierichards** [comment]
Ahhhhh dangit you're right. The demo needs to make a note of that. Closing, as this is a different issue ;]

**Comment by molant** [comment]
The demo should already have a note at the very beginning and a link to about:flags

-----Original Message-----
