### ISSUE TITLE
css3filters demo needs to have a notice about turning on the feature in about:flags

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#105]

**Comment by molant** [comment]
It should already have a note at the very beginning with a link to about:flags

-----Original Message-----

**Comment by molant** [comment]
There is already a warning on the top that gets displayed if the demo doesn't detect support for CSS3Filters:

![image](https://cloud.githubusercontent.com/assets/606594/9400971/143742c6-477d-11e5-9902-27adfc6bb1f5.png)

**Comment by melanierichards** [comment]
Hmm, wonder why I thought I didn't see that. Must be going crazy.
