### ISSUE TITLE
Linked website is not working

### ISSUE THREAD

**Issue by ePirat** [MicrosoftEdge/Demos-old#143]
The Website linked in the repo description (http://testdrive.microsoftedge.com/)
is not working properly here, it does a bunch or redirects:

First to https://dev.modern.ie/testdrive/demos/ and from there to https://dev.windows.com/en-us/microsoft-edge/testdrive/demos/ and from there to:

```
Location: /redirect?url=..%2F
```

So I end up at https://dev.windows.com/redirect?url=..%2F which is an error page.

**Comment by ePirat** [comment]
The following: http://dev.modern.ie/testdrive/
does work fine, so maybe that one should be used instead.

**Comment by molant** [comment]
Fixed. Thanks!
