### ISSUE TITLE
Colouring book demo - text not fully responsive

### ISSUE THREAD

**Issue by herenhuang** [MicrosoftEdge/Demos-old#158]
The paragraph explaining the demo, and the picture beneath of where to click into web notes gets cut off based on different page sizing for this demo: https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/coloringbook/

![image](https://cloud.githubusercontent.com/assets/4635815/16500283/ce895442-3eb8-11e6-89ed-ae763313a1e4.png)

![image](https://cloud.githubusercontent.com/assets/4635815/16500318/f60211e4-3eb8-11e6-8a2b-64c064e05c12.png)

**Comment by alrra** [comment]
Closing as this seems to be fixed:

![](https://cloud.githubusercontent.com/assets/1223565/21484228/de4512ec-cb97-11e6-93b5-aa060eaafa2d.gif)

---

@herenhuang Thanks for opening this issue, and sorry for the delayed answer!
