### ISSUE TITLE
SVG Gradient Background Demo - Redesign

### ISSUE THREAD

**Issue by ststimac** [MicrosoftEdge/Demos-old#161]
Kicking off redesign/reskin of old demos.

**Comment by ststimac** [comment]
I am pretty sure that the jscolor demo being utilized here is not working on the site.

**Comment by ststimac** [comment]
First round of mockups.
![demo_svg_gradient-01](https://cloud.githubusercontent.com/assets/18073131/18405129/4147f54c-76a4-11e6-8e1a-50993f4a09d2.png)

![demo_svg_gradient-02](https://cloud.githubusercontent.com/assets/18073131/18405010/4a240152-76a3-11e6-9a28-9734019b7b66.png)

**Comment by ststimac** [comment]
@melanierichards adding you for visibility, if you want to give input on these SVG gradient background demo mock ups.

**Comment by melanierichards** [comment]
This looks so much better!

@ststimac @molant this would be a functional change but it would be good to pick the browser support you want, because what the generator provides might be a little overkill depending on what you support. This could be as simple as choosing between just 2 values: "Modern browsers" and "As much support as possible". The code comment in the CSS would be more explicit about which browsers were supported. The wording can be changed but that's the general idea.

**Comment by ststimac** [comment]
@melanierichards @molant  So I'm starting to recode this and the entire thing uses table, td, and tr which is throwing off the javascript when I try move things around or rename or restructure. 

If I do all the HTML/CSS stuff and add notes, can someone else hook up the Javascript? Or are we trying to keep the code that's already there intact as much as possible?

**Comment by molant** [comment]
@ststimac we can update the JS. Do you want to try to improve your JS skills? Can guide you in the process :)

**Comment by ststimac** [comment]
@molant yes I do. Should I focus on the HTML/CSS first and then let you know when I'm ready to get going with the JS edits?

**Comment by molant** [comment]
Yup

**Comment by ststimac** [comment]
Just an FYI: the old SVG demo is still up on the site & is completely broken. Assuming something with the Indigo update affected the old styling.

**Comment by melanierichards** [comment]
Can we prioritize updating this one, then?

**Comment by ststimac** [comment]
The PR for this update was already merged ~1.5 weeks ago. Anton how long does it take for the update to show?

**Comment by melanierichards** [comment]
HA I thought we had already done this, thought I was going crazy...

**Comment by molant** [comment]
It is showing up, no headers because of the `config.json` but we haven't added the script for the light header :(

**Comment by ststimac** [comment]
@molant there's something else with the JS not working I think. A color picker is supposed to appear & the background of the input boxes for the two colors that are there are white instead of their corresponding colors. :(

**Comment by ststimac** [comment]
Closing. This has been merged and is live on the portal.
