### ISSUE TITLE
Style spellchecking

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#17]

**Comment by melanierichards** [comment]
I think this got closed by accident.

**Comment by alrra** [comment]
This may be resolved in #257? 

(issue in which I'm trying to fix #236 and #224)

---

I see this is already assigned. I sincerely apologize, but I just discovered this issue, and the weird part is that I actually searched before hand and somehow completely missed this. :(

**Comment by alrra** [comment]
Closing this in favor of #257.
