### ISSUE TITLE
Where is Caption Maker code?

### ISSUE THREAD

**Issue by LordBritt** [MicrosoftEdge/Demos-old#177]
I can't see the caption maker code in this repository. The Browse button isn't doing anything (for me) so I'd like to take a look at the code and try and work out what's up.
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/captionmaker/

**Comment by molant** [comment]
Old demos are in https://testdrive-archive.azurewebsites.net.
Caption maker is in: https://testdrive-archive.azurewebsites.net/Graphics/CaptionMaker/
