### ISSUE TITLE
Penguin Mark: Button is div soup

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#182]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/penguinmark/

Can't reach test your browser with the keyboard as it is just a div. No a11y info applied either (ARIA, etc)

Recommendation:

Use a good to god, honest, button element

**Comment by dstorey** [comment]
Try again button at end has the same issue

**Comment by alrra** [comment]
Closing in favor of #248.
