### ISSUE TITLE
Touch Effects: minimal header?

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#188]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/toucheffects/

Should this use the minimal header rather than the site header?

**Comment by dstorey** [comment]
Looks like this breaks the fly out menu for settings as it overlaps the fat footer.

**Comment by melanierichards** [comment]
Yes, absolutely! I think this might be something that needs to be set in admin cc @kypflug @sarvaje
