### ISSUE TITLE
Music Lougue: just loads blank page

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#209]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/musiclounge/

Tested in Edge and Chrome. Just loads a blank page.

**Comment by deltakosh** [comment]
Ping @davrous

**Comment by molant** [comment]
I think this is an issue when we copy the files in production. Don't know why there is a weird character added and the library fails to load. 
CC @sarvaje

**Comment by sarvaje** [comment]
I'll take a look

**Comment by sarvaje** [comment]
@deltakosh @molant @davrous fixed the demos updater job. This will be fixed when I deploy to production (hopefully tomorrow). Meanwhile I replace the corrupted library file.

**Comment by deltakosh** [comment]
Thanks!

**Comment by sarvaje** [comment]
This should be fixed with the last deployment of EdgePortal.
Closing!
