### ISSUE TITLE
Binary file inspector: Layout totally borked

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#221]
Same as previous issue. When increase base font size to 32px the contents overlap, this time making page unusable.

**Comment by melanierichards** [comment]
@alrra have you done any work on this issue yet? I was thinking of assigning to myself / doing a more generalized design update.

**Comment by alrra** [comment]
> have you done any work on this issue yet? 

@melanierichards No, feel free to take it!
