### ISSUE TITLE
Sudoku: Some text scales, others don't

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#223]
When set base font size to 32px most text stays the same size. The button text scales however, but their containing box stay the same size, breaking the layout in places.

**Comment by melanierichards** [comment]
@alrra are you already working on this? I was planning to redesign this Sudoku demo in another style anyway, so I can pick up this issue if you're not already working on it.

**Comment by alrra** [comment]
>  so I can pick up this issue if you're not already working on it.

@melanierichards I was playing with the code a bit, but sure, feel free!

**Comment by melanierichards** [comment]
@alrra cool, thanks!
