### ISSUE TITLE
setImmediateSorting: Label text not unique on buttons

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#237]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/setimmediatesorting/

All buttons use Run Test.

One way to fix would be to add a ID to the subtitle above, and add an aria-labelledby="buttonID subtitleID" so that for example it would read "Run Test HTML4 (~15ms Timers)"

**Comment by alrra** [comment]
Closing this in favor of https://github.com/MicrosoftEdge/Demos/pull/280.
