### ISSUE TITLE
3DTransforms: various labelling issues

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#247]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/3dtransforms/

* Labels for sliders are table cells rather than labels. We probably want to replace with true range controls and labels to make it easier to make accessible. 
* Similar issue with label for radios
* Buttons such as delete, move up and move down have no text or aria-label.

**Comment by alrra** [comment]
@dstorey @sarvaje This demo is external, namely, it's from https://testdrive-archive.azurewebsites.net/Graphics/hands-on-css3/hands-on_3d-transforms.htm.
