### ISSUE TITLE
ORTC demo: Alert is broken

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#307]
Alert, which seems to be for warning browsers they don't support ORTC, is visually and functionally broken. 

Tested in Safari and Chrome 
![screen shot 2016-12-29 at 7 43 11 pm](https://cloud.githubusercontent.com/assets/465069/21553215/12055272-cdff-11e6-93d5-71e51f77e15f.png)

**Comment by ShijunS** [comment]
Chatted with @molant.  He will help fix the issue.

**Comment by molant** [comment]
This is fixed in the live site now
