### ISSUE TITLE
Fish links should mention fish

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#308]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/fishietank/

Links to change fish number is as such:

`<a class="control" href="javascript:createFish(20);">20</a>`

Suggested fix:

* add aria-label="20 fish"

Alternatively could hook into the scoreLabel label to add fish with aria-labelledby but that is probably more code than just repeating fish for each.

**Comment by alrra** [comment]
Closing this in favor of #321.
