### ISSUE TITLE
Let it snow and others: new pause button needs associated with audio element

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#318]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/letitsnow/
Currently when you land on the audio element there is no way of knowing there is a pause button in the document.

I believe you need aria attributes to associate the pause button to the audio element. I will look up what exactly is needed for that later if whoever is fixing it can't find it.

**Comment by alrra** [comment]
Using [`aria-controls`](https://www.w3.org/TR/wai-aria/states_and_properties#aria-controls) on the button doesn't seem to do anything. :(

**Comment by dstorey** [comment]
@alrra if that isn't doing anything then just put the pause button directly after the audio element for now.
