### ISSUE TITLE
Twillo: Timer not hidden from screen reader in default hidden state

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#324]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/twilioortc/

`<div id="timer" class="disabled">0:00</div>`

it is hidden with opacity and left: -80px; It is still in the a11y tree and is read by the screen reader as 0:00 with no context.

Fix:

* Hide it correctly (either display: none or hidden attribute) and update when the .disabled class is removed (presumably when the call starts)
* If when making a call it just has the duration as a number, extra text needs to be added (via aria-label or whatever) to say that the number is the duration of the call.

**Comment by alrra** [comment]
@dstorey @sarvaje This demo is external, namely, it's from https://twilio-ahoy.herokuapp.com/edge-ortc.

**Comment by dstorey** [comment]
Might be one that @ShijunS was involved with.
