### ISSUE TITLE
Web audio tuner: MathML examples don't show

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#328]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/webaudiotuner/

MathJax is being used, but I can't see the text being rendered. Tested on Firefox, Safari and Chrome on Mac.

**Comment by alrra** [comment]
> I can't see the text being rendered.

That happens because the rendered output is stored inside of:

```html
<nobr aria-hidden="true">...</nobr>
```

and in [`demotemplate.css`](https://edgeportal.blob.core.windows.net/media/demotemplate.css) we have the following:

```css
[aria-hidden="true"] {
    display: none;
}
```

---

From https://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden

> aria-hidden (state)
> 
> Indicates that the element and all of its descendants are not visible or perceivable to any user as implemented by the author. See related aria-disabled.

IMHO, the `MathJax` library is in the wrong here by using `aria-hidden="true"`.

**Comment by alrra** [comment]
From https://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden

> aria-hidden (state)
> 
> Indicates that the element and all of its descendants are not visible or perceivable to any user as implemented by the author. See related aria-disabled.

IMHO, the `MathJax` library is in the wrong here by using `aria-hidden="true"`.

**Comment by dstorey** [comment]
@alrra seems weird they're hiding it in mathjax, but it is a bug on EdgePortal that we hide aria-hidden by default. That was a quick hack to work around some issues, and needs to be replaced with the hidden attribute instead (but we didn't have time at the time to find all those to replace and test)

**Comment by dstorey** [comment]
It may be possible to remove the display: none from the demo template without much worry as most of the demos haven't been using ARIA so there is less to break (and we're doing a lot of testing right now anyway)

**Comment by alrra** [comment]
> It may be possible to remove the `display: none` from the demo template

Cc @melanierichards

**Comment by melanierichards** [comment]
@dstorey @alrra the demo template is a compiled version of the live CSS on the site. So changing it there would impact the whole site. It would be better to do an override specific to this demo.

**Comment by alrra** [comment]
> It would be better to do an override specific to this demo.

@dstorey @melanierichards Done in https://github.com/MicrosoftEdge/Demos/pull/339.
