### ISSUE TITLE
Empty anchors on a number of demo interstitial pages

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#329]
Empty anchors in the interstitial page: https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/dolbyaudioexperience/

`<a name="dolby-audio"></a>` and `<a name="browser-capabilities"></a>`

Not sure why they are being used. Looks like it is for jump links. 

Should just add IDs to the headings below if want to be able to link to that part of the page.

**Comment by alrra** [comment]
@dstorey 

1) The code that seems to be on our side is not in this repository.
2) This demo is external, namely, it's from: http://audioexperience.dolby.com/.
3) See also: https://github.com/MicrosoftEdge/Demos/issues/297#issuecomment-269548406.

---

Cc: @sarvaje

**Comment by alrra** [comment]
Cc: @sarvaje

**Comment by dstorey** [comment]
Same issue on https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/hover/

**Comment by dstorey** [comment]
And https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/flightarcade/
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/assassins/
