### ISSUE TITLE
Css3 Filters are not working on IE 10 and edge

### ISSUE THREAD

**Issue by rajasajidmanzoor** [MicrosoftEdge/Demos-old#371]
Css3 Filters are not working on IE 10 and edge

Here is how it displays on IE

![image](https://user-images.githubusercontent.com/5917783/28263824-d2214422-6b01-11e7-9dbc-dbb919ce24a3.png)

**Comment by molant** [comment]
Css filters were added first on edge so this is the expected behavior.

**Comment by rajasajidmanzoor** [comment]
@molant  how a thing that is not working can be expected behavior?

CSS3 filters are not working on IE 10 and 11. You need to fix  this.  Closing and issue is not the solution.

**Comment by molant** [comment]
@rajasajidmanzoor I don't understand your comment. Are you suggesting we should port back all the new feature edge has to previous versions of IE? That is not going to happen.

**Comment by alrra** [comment]
> CSS3 filters are not working on IE 10 and 11. You need to fix this. Closing and issue is not the solution.

@rajasajidmanzoor The scope of these demos are to showcase new features that didn't existed before (be that in older browsers, or in older browser versions).

As @molant said, support for CSS3 filters didn't exist in IE 10 and 11, same as it didn't exist in older version of Chrome, Firefox, etc., so there is nothing to fix here.

**Comment by rajasajidmanzoor** [comment]
@alrra  @molant CSS3 filters are working fine in Chrome, FF and other browsers.
BUt They are not working in IE 10, IE 11 and Edge.  You can go and test these your self,.
