### ISSUE TITLE
Minifying demo assets

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#381]
With these demos, we want to:

1. Teach new approaches/tech
2. Deliver a nice experience, which includes performance

To balance these two desires, I want to propose serving minified CSS/JS assets, while providing a non-minified experience that devs can peek through.

I'm thinking that the demo author will have a [grunt watch](https://github.com/gruntjs/grunt-contrib-watch) process running, hooked up to [uglify](https://github.com/gruntjs/grunt-contrib-uglify) and [cssmin](https://github.com/gruntjs/grunt-contrib-cssmin). These will concatenate and minify the demo template JS/CSS with the demo-specific JS/CSS. The un-minified versions will of course be accessible through the repo, but we can also have a code comment with the file name in the head of the demo, OR perhaps there is some way to insert this into the minified files w/o also having this portion itself minified.

@molant thoughts? Issues with this?

**Comment by molant** [comment]
Just chat with @melanierichards and we are not going to do this for now. Too many changes in different places and not very high in the priority list.
