### ISSUE TITLE
[Variable fonts] Decovar animation

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#387]

**Comment by FremyCompany** [comment]
@melanierichards What was this about exactly again? I'm probably gonna take this one.

**Comment by gregwhitworth** [comment]
@FremyCompany this is mine ;)

**Comment by melanierichards** [comment]
DANG! :D

**Comment by FremyCompany** [comment]
Yours it is :)

**Comment by melanierichards** [comment]
@FremyCompany I just realized I forgot to make the issue about the animated headings, will write that up for you!

**Comment by melanierichards** [comment]
Closing because it's completed!
