### ISSUE TITLE
Missing sandbox demo

### ISSUE THREAD

**Issue by gcbw** [MicrosoftEdge/Demos-old#409]
This page https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673561(v=vs.85) links to a sandbox demo that is nowhere to be found.

> For a hands-on demonstration of HTML5 Sandbox in action, see Defense in Depth: HTML5 Sandbox on the IE Test Drive.

**Comment by alrra** [comment]
@gcbw The demo seem to be [here](https://testdrive-archive.azurewebsites.net/HTML5/sandbox/Default.html).

> This page https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/hh673561(v=vs.85)

@erikadoyle @mattwojo Any way we can update the link in the above page, even though those pages are deprecated?

**Comment by erikadoyle** [comment]
Thanks @gcbw for raising the issue and @alrra for the fix! Updated now.
