### ISSUE TITLE
Service unavailable error on several demos

### ISSUE THREAD

**Issue by erikadoyle** [MicrosoftEdge/Demos-old#410]
I'm getting HTTP 503 errors when trying to load several of our testdrive demos, including:

- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/audiomixer/
- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/microphone/
- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/familysearch/

*Not an exhaustive list; probably some others too

**Comment by molant** [comment]
This is fixed now. Thanks!
