### ISSUE TITLE
Some demos render as blank pages

### ISSUE THREAD

**Issue by erikadoyle** [MicrosoftEdge/Demos-old#411]
Several demos are loading as empty documents without support files:

- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/musiclounge/
- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/speechsynthesis/

*Not an exhaustive list; maybe others too

**Comment by briancodes** [comment]
The Math API Demo is also not loading

- https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/math/

Error: 
```
Correlation ID: ffc313ab-f0cd-4b25-bdc5-2f3a319ad4aa
Correlation vector: mj9ua32rnUWV3BKm.0
App server:
Time: 15 Aug 2018 03:29:57 -07:00
```

**Comment by molant** [comment]
This is fixed now. Thanks!
