### ISSUE TITLE
Update demotemplate CSS reference to file on Azure

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#44]
- [x] @supports
- [x] blobbuilder
- [x] css3filters
- [x] familysearch

**Comment by melanierichards** [comment]
@molant this CSS file is not loading: http://edgeportal.blob.core.windows.net/media/demotemplate.css. Is the CSS possibly in a password-protected directory?

**Comment by molant** [comment]
shouldn't be, everything else is loading :s

**Comment by melanierichards** [comment]
Hmm ok I don't know what changed but now it's loading for me. ¯_(ツ)_/¯
