### ISSUE TITLE
Typedarrays is not well wrapped

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/Demos-old#48]
footer in testdrive gets put into the right side. Probably needs to be wrapped in a div with container class

**Comment by sarvaje** [comment]
@molant do you have the correct version? I compare with other demos and I think the footer is ok:
![image](https://cloud.githubusercontent.com/assets/1581288/7428917/c9fcdcba-eff8-11e4-9344-01c43aba411f.png)

**Comment by molant** [comment]
My bad, it is working
