### ISSUE TITLE
Music Lounge needs intro text

### ISSUE THREAD

**Issue by melanierichards** [MicrosoftEdge/Demos-old#52]
Needs some instructions about dragging the cubes into the center.

Ideally:
- This demo would be a full-screen guy with an interstitial page.
- We'd have a longer write-up about how it was made.

For now just need some indication of what you're supposed to do. Assigning to @molant to reach out to demo owner (I think David Catuhe?).

**Comment by molant** [comment]
One of the things I would like to add is a button to go to full screen. This could be reused by lots of demos.
ATM hosted demos can't have interstitial pages so not sure we are going to be able to have this. Also @deltakosh just had a baby girl and guess he wants to spend time with her :)

**Comment by deltakosh** [comment]
Thanks dude! I appreciate:)

**Comment by molant** [comment]
No need for intro text, demo runs in full screen mode now
