### ISSUE TITLE
webaudiotuner samples contain invalid code

### ISSUE THREAD

**Issue by domenic** [MicrosoftEdge/Demos-old#71]
In particular, the repeated use of variables before they are declared.

The first time this occurs is the AnalyserNode sample, where streamReceived is used before it is declared. This will result in passing `undefined` for that callback.

To fix this, either order the declarations before the calls, or switch to function declarations, which benefit from hoisting.

**Comment by quimbs** [comment]
I have moved a few things around in the gists and added a few comments pointing to other sections in the demo. Those code snippets were never intended to be entirely functional on their own, but a way to explain each step and show that portion of the demo side by side. This means that the initialization of some variables will happen in other code snippets in the page. I hope those comments make it more clear.

I will also mention this in the demo just in case.

Thank you for the feedback.
