### ISSUE TITLE
webaudiotuner samples should encourage promise version usage

### ISSUE THREAD

**Issue by domenic** [MicrosoftEdge/Demos-old#72]
Per http://blogs.windows.com/msedgedev/2015/05/13/announcing-media-capture-functionality-in-microsoft-edge/,

> Based on the W3C spec, we support both the promise-based getUserMedia() method and the callback-based getUserMedia() method. The callback-based method allows an easier transition if you have a webpage using the interface already (although it might be a vendor-prefixed version). **We encourage web developers to use the promise-based approach to follow the industry trend for new interface design styles on the web.**

An easy way to do this would be to have a quick shim, like

``` js
var getUserMedia = navigator.mediaDevices.getUserMedia ?
  navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices) :
  function (constraints) {
    return new Promise(function (resolve, reject) {
      navigator.getUserMedia(constraints, resolve, reject);
    });
  };
```

Then you can use the promise version uniformly (via `getUserMedia(...).then(...)`), and at the same time talk a bit about how Edge is leading the way in having the new promise-based method :)

**Comment by molant** [comment]
@quimbs, want to do this one?

**Comment by quimbs** [comment]
I'm busy with something else right now, but will definitely take this one.
