### ISSUE TITLE
Migrate the Fishbowl demo from the old site

### ISSUE THREAD

**Issue by charlesjmorris** [MicrosoftEdge/Demos-old#74]
Transferring request from https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/8478523-fix-the-link-to-the-html5-fishbowl-benchmark

**Comment by matthargett** [comment]
I can't find this on the testdrive site, when will the current github repo be pushed to the live site?

**Comment by molant** [comment]
No ETA at the moment for this but it is on our backlog
