### ISSUE TITLE
Request to migrate maze solver benchmark from old site 

### ISSUE THREAD

**Issue by aethanyc** [MicrosoftEdge/Demos-old#80]
http://ie.microsoft.com/testdrive/Performance/MazeSolver/Default.html

This is a useful performance test for browsers, especially for Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=776190

**Comment by aethanyc** [comment]
@molant: Is there a link to the MazeSolver demo on the new site?

BTW, I found that the MazeSolver depends on some external css and js files which are not included in the patch. https://github.com/MicrosoftEdge/Demos/blob/0f77fdd0238dadc5fbcc9bc943ddc19d4ad51e6b/mazesolver/Default.html#L9-L13

**Comment by molant** [comment]
No, I think the readme.md says the reason why it isn't in the new website for now (basically it doesn't work and we need to do some changes). I'll take a look at the css/js. I think that the missing ones are safe to ignore (but maybe I'm wrong).

Thanks! 

-----Original Message-----

**Comment by aethanyc** [comment]
Got it. Thank you for bringing MazeSolver back.

**Comment by molant** [comment]
@aethanyc I've added the old shared files. Give it a try now

**Comment by aethanyc** [comment]
@molant: It works. Thank you :-)
