### ISSUE TITLE
Unterminated promise-chains hide errors in PhotoCapture demo

### ISSUE THREAD

**Issue by jan-ivar** [MicrosoftEdge/Demos-old#83]
Two chains are unterminated (missing `.catch(func)` at the tail):  `navigator.mediaDevices.enumerateDevices().then(devicesCallback);`.

This causes errors from `navigator.mediaDevices.enumerateDevices()` and any errors (even coding errors and exceptions) from the `devicesCallback` function to be suppressed (hidden).

Quick-fix: `navigator.mediaDevices.enumerateDevices().then(devicesCallback).catch(getUserMediaErrors);`.

**Comment by molant** [comment]
@jan-ivar in what demo?

**Comment by jan-ivar** [comment]
Oh sorry https://github.com/MicrosoftEdge/Demos/blob/master/photocapture/scripts/demo.js#L148

**Comment by ShijunS** [comment]
@jan-ivar Thanks for the feedbacks!  We will update the code accordingly.

**Comment by molant** [comment]
Thanks!
