### ISSUE TITLE
photocapture: use adapter.js to enable modern-style code in all browsers

### ISSUE THREAD

**Issue by fippo** [MicrosoftEdge/Demos-old#90]
I [just added](https://github.com/webrtc/adapter/pull/102) support for using video.srcObject in Chrome and Firefox to adapter.js. This allows to reduce the code in https://github.com/MicrosoftEdge/Demos/blob/master/photocapture/scripts/demo.js#L26-L31 to just setting the srcObject, just as the spec shows. Showing backward compat cruft in demos is bad as developers will pick this up eventually.

Using adapter will also enable the navigator.mediaDevices.enumerateDevices functionality as well as promise-based navigator.mediaDevices.getUserMedia.
In addition, this will avoid [ths breakage](https://code.google.com/p/chromium/issues/detail?id=511082) when/if Chrome removes the command line flag needed for navigator.mediaDevices.getUserMedia (which hopefully will not happen while only legacy constraints are supported)

@ShijunS: not sure if it's best to grab a local copy of adapter.js instead of fetching the latest version from github.

**Comment by jan-ivar** [comment]
+1

**Comment by molant** [comment]
Hi @fippo, regarding having a local copy of adapter.js our guidance from LCA is not to have any third party libraries in the repo. We can link to CDNs or have bower packages. IMO the fastest solution will be to host it in cdnjs.com (haven't found it). The other option will be to have a bower package but it will take me some time to update the infrastructure so I would like to avoid it if possible.

Thanks a lot!
