### ISSUE TITLE
Port Caption Maker

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#92]
We need to port caption maker to the new site (preferably with a visual makeover, and any enhancements to our captioning support) ie.microsoft.com/testdrive//Graphics/CaptionMaker
A few places link to it as a useful resource.

**Comment by tyrrell** [comment]
Bump. Would greatly appreciate this. Cannot find the tool anywhere.

**Comment by CoWinkKeyDinkInc** [comment]
:+1: Yes please, it is a very useful tool and be great having an offline version.

**Comment by Cduocor** [comment]
Cduocor Dung 4hour ago

**Comment by Cduocor** [comment]
Cduocor 4 hours ago

**Comment by Cduocor** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/13703380/9547631/bf433938-4dc5-11e5-9542-79f975151305.jpg)

**Comment by CoWinkKeyDinkInc** [comment]
Really?

**Comment by molant** [comment]
@CoWinkKeyDinkInc @dstorey it is available now in https://dev.modern.ie/testdrive/demos/captionmaker/
